### ISSUE TITLE
 Error while formatting

### ISSUE THREAD

**Issue by T1MOXA** [peace-maker/sm-methodmapize#1]
```
Traceback (most recent call last):
  File "MethodMap\methodmapize.py", line 23, in <module>
    code = f.read()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 78259: character maps to <undefined>
```

**Comment by peace-maker** [comment]
Fixed in your PR #2
